version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8081

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
    volumes:
      - ./frontend:/app
      - /app/node_modules